name: CI_ARCH

on:
  push:
      branches: [develop]
  pull_request:
      branches: [develop]

jobs:
  build:
    strategy:
      matrix:
        include:
          - xcode: "16.0"
            deployment_target: "production"
    runs-on:  self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: ./other/download_libs.sh --arch arm64

      - name: Build
        run: xcodebuild -project iina.xcodeproj ONLY_ACTIVE_ARCH=YES -scheme iina -configuration Nightly ${{ matrix.deployment_target }}
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

      - name: Archive
        run: tar cvJf ~/iina.tar.xz -C /Users/mahamudul/Library/Developer/Xcode/DerivedData/iina-csbkugdtxazzqogjnydbothqrvib/Build/Products/IINA.app 

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IINA
          path: ~/iina.tar.xz
